FROM debian:jessie
MAINTAINER Raphael Catolino "raphael.catolino@gmail.com"

# Add node sources
RUN echo 'deb http://deb.nodesource.com/node_5.x jessie main' > /etc/apt/sources.list.d/node.list
COPY nodesource.gpg.key ./nodesource.gpg.key
RUN apt-key add nodesource.gpg.key

# Install dependencies
RUN export DEBIAN_FRONTEND=noninteractive && \
  apt-get -qy update && apt-get -qy install \
  build-essential \
  git \
  libicu-dev \
  nodejs \
  python

# Add dedicated irc user
RUN useradd -m -d /var/lib/ircbridge -s /usr/sbin/nologin ircbridge
WORKDIR /var/lib/ircbridge
COPY start.sh ./start.sh
RUN chmod 755 ./start.sh
USER ircbridge

# Install the bridge
RUN npm install matrix-appservice-irc

# The configuration will live in /data/irc
VOLUME ["/data/irc"]
VOLUME ["/data/shared"]

EXPOSE 5487
ENTRYPOINT ["/var/lib/ircbridge/start.sh"]
CMD ["start"]
