version: '2.1'

services:
  synapse:
    image: silviof/docker-matrix
    expose:
      - "8008"
    ports:
      - "9388:8448"
    restart: on-failure:3
    stop_grace_period: 2s
    healthcheck:
      test: ["CMD-SHELL", "ss -tlpn | grep 8008"]
      interval: 2s
      timeout: 5s
      retries: 3
    volumes:
      - /data/synapse:/data
      - /data/ssl:/ssl
      - /data/shared:/shared

  irc:
    build: ./appservice-irc
    depends_on:
      synapse:
        condition: service_healthy

    image: matrix-appservice-irc
    expose:
      - "5487"
    restart: on-failure:3
    stop_grace_period: 2s
    volumes:
      - /data/shared:/shared
      - /data/irc:/data

